export interface UserProfile {
  cod_user: string
  cod_consultant: string
  fullname: string
  names: string
  firstName: string
  lastName: string
  cod_country: string
  country_name: string
  cod_region: string
  cod_zone: string
  section: string
  cod_role: string
  role: string
  identification_document: string
  level: string
  cub: string
  landline: string
  cellphoneNumber: string
  email: string
  latitude: string
  longitude: string
  cod_level: string
  id_level: string
  cod_territory: string
  __typename: string
}

/*
cod_user: string
  password: string
  names: string
  fullname: string
  firstName: string
  lastName: string
  cub: string
  role: string
  cod_role: string
  profile: string
  cod_country: string
  country_name: string
  cod_region: string
  cod_zone: string
  section: string
  landline: string
  cellphoneNumber: string
  tutorial: number
  name_boss: string
  cod_message: string
  message: string
  logId: number
  is_leader: boolean
  date_end_admin: string
  zoneActive: number
  digit_check: string
  identification_document: string
  email: string
  level: string
  other_cellphone: string
  consultantID: string
  flagDigitCheck: boolean
  latitude: string
  longitude: string
  cod_territory: string
  section_manager_leader: string
  georeferenciation: string
  cod_consultant: string
  cod_level: string
  id_level: number
  */
